steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node:16
    entrypoint: npm
    args: ['run', 'build']
#  next step is responsible for uploading the artifacts to cloud storage
#  Unfortunately the artifacts directive can't recursively copy a folder.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'cp', '-r', 'dist/*', 'gs://site.lifepete.com' ]
